# Generated by Django 4.1.3 on 2022-11-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.FileField(blank=True,
                                   default=None,
                                   null=True,
                                   upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True,
                                   default=None,
                                   max_length=256,
                                   null=True),
        ),
    ]
