# Generated by Django 4.1.3 on 2022-11-23 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_avatar_image_alter_tag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='createquestion',
            name='created_at',
            field=models.TimeField(auto_now_add=True,
                                   default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createquestion',
            name='updated_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
