# Generated by Django 4.1.3 on 2022-11-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question',
         '0003_createquestion_created_at_createquestion_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createquestion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='createquestion',
            name='updated_at',
        ),
    ]
