# Generated by Django 4.1.3 on 2022-11-23 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_remove_createquestion_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
