# Generated by Django 4.1.3 on 2022-11-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_questionvote_createanswer_answervote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answervote',
            name='type_id',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'indiffence'),
                         (1, 'condemn'),
                         (2, 'approve'),
                         (3, 'right')],
                default=0),
        ),
        migrations.AddField(
            model_name='questionvote',
            name='type_id',
            field=models.PositiveSmallIntegerField(choices=[(0, 'indiffence'),
                                                            (1, 'condemn'),
                                                            (2, 'approve')],
                                                   default=0),
        ),
    ]
